# FROM node:12.7-alpine AS build
# WORKDIR /usr/src/soa-client
# COPY package.json package-lock.json ./
# RUN npm install
# COPY . .
# CMD npm start
# ### STAGE 2: Run ###
# FROM nginx:1.17.1-alpine
# COPY nginx.conf /etc/nginx/nginx.conf
# COPY --from=build /usr/src/soa-client/dist/client /usr/share/nginx/html