version: '3'
services:
  api-gateway:
    build: './api-gateway'
    ports:
      - "3000:3000"
      - "8080:8080" 
  appointment:
    build: './appointment'
    ports:
      - "3001:3000"
  auth:
    build: './auth'
    ports:
      - "3002:3000"
  imgur-photo:
    build: './imgur-photo'
    ports:
      - "3003:3000"
  static-data:
    build: './static-data'
    ports:
      - "3004:3000"